# Generated by Django 4.1.3 on 2022-11-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'NullMote'), (1, 'WMote'), (2, 'EMote'), (3, 'BM-GMote')], default=0)),
                ('sector', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_lh', models.FloatField()),
                ('totall', models.FloatField()),
                ('min_wh', models.FloatField()),
                ('totalwh', models.FloatField()),
                ('min_ppm', models.FloatField()),
                ('collectdate', models.DateTimeField()),
                ('mote', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.motes')),
            ],
        ),
    ]
