# Generated by Django 4.0.5 on 2022-08-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='', max_length=255)),
                ('instalh', models.FloatField()),
                ('totall', models.FloatField()),
                ('collectdate', models.DateTimeField()),
            ],
        ),
    ]
