# Generated by Django 4.0.5 on 2022-08-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='', max_length=255)),
                ('minwh', models.FloatField()),
                ('totalwh', models.FloatField()),
                ('collectdate', models.DateTimeField()),
            ],
        ),
    ]
