# Generated by Django 4.1.3 on 2022-11-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_data_collect_date_alter_data_min_lh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='collect_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='min_lh',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='min_ppm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='min_wh',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='total_l',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='total_wh',
            field=models.FloatField(default=0),
        ),
    ]
