# Generated by Django 4.0.5 on 2022-08-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='dispname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='water',
            name='dispname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
