# Generated by Django 4.0.5 on 2022-08-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_energy_dispname_water_dispname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='dispname',
            field=models.CharField(choices=[('1', 'WMote01'), ('2', 'WMote02')], default='', max_length=255),
        ),
    ]
