# Generated by Django 4.1.3 on 2022-12-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_data_collect_date_alter_data_min_lh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motes',
            name='type',
            field=models.IntegerField(choices=[(0, 'NullMote'), (1, 'WMote'), (2, 'EMote'), (3, 'GMote-BM')], default=0),
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mean', models.FloatField()),
                ('Median', models.FloatField()),
                ('STD', models.FloatField()),
                ('CV', models.FloatField()),
                ('Max', models.FloatField()),
                ('Min', models.FloatField()),
                ('FQ', models.FloatField()),
                ('TQ', models.FloatField()),
                ('mote', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.motes')),
            ],
        ),
    ]
