# Generated by Django 4.0.5 on 2022-08-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_water_dispname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='dispname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
