# Generated by Django 4.0.5 on 2022-08-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_water_dispname'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispname', models.CharField(default='', max_length=255)),
                ('wMean', models.FloatField()),
                ('wMedian', models.FloatField()),
                ('wSTD', models.FloatField()),
                ('wCV', models.FloatField()),
                ('wMax', models.FloatField()),
                ('wMin', models.FloatField()),
                ('wFQ', models.FloatField()),
                ('wTQ', models.FloatField()),
            ],
        ),
    ]
