# Generated by Django 4.0.5 on 2022-08-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_waterstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispname', models.CharField(default='', max_length=255)),
                ('eMean', models.FloatField()),
                ('eMedian', models.FloatField()),
                ('eSTD', models.FloatField()),
                ('eCV', models.FloatField()),
                ('eMax', models.FloatField()),
                ('eMin', models.FloatField()),
                ('eFQ', models.FloatField()),
                ('eTQ', models.FloatField()),
            ],
        ),
    ]
