# Generated by Django 4.1.3 on 2022-11-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_energy_id_alter_energystats_id_alter_water_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='energy',
            name='dispname',
        ),
        migrations.RemoveField(
            model_name='energy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='energystats',
            name='dispname',
        ),
        migrations.RemoveField(
            model_name='water',
            name='dispname',
        ),
        migrations.RemoveField(
            model_name='water',
            name='location',
        ),
        migrations.RemoveField(
            model_name='waterstats',
            name='dispname',
        ),
        migrations.AddField(
            model_name='energy',
            name='mote_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.motes'),
        ),
        migrations.AddField(
            model_name='energystats',
            name='mote_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.motes'),
        ),
        migrations.AddField(
            model_name='water',
            name='mote_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.motes'),
        ),
        migrations.AddField(
            model_name='waterstats',
            name='mote_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.motes'),
        ),
    ]
